### ISSUE TITLE
preventLoad fails with data path

### ISSUE THREAD

**Issue by dman777** [PolymerElements/iron-image#119]
### Description
iron-image 2.1.1 / Polymer 1.*
`preventLoad` is not effective when data path is false. 

### Expected outcome

preventLoad should prevent load with data path.

### Actual outcome

request for image goes out event though preventLoad is true. 

### Steps to reproduce
When the element is active, `preventLoad` will not prevent iron image from doing a request when using a data path.

```html
            <!-- if in edit mode -->
            <template is="dom-if" if="[[edit]]">

              <iron-image
                hidden$="[[!editState(uploadState.*, index, 'edited')]]"
                prevent-load="[[!editState(uploadState.*, index, 'edited')]]"
                src="[[getImage(uploadState.*, index, 'value')]]"
                sizing="cover"
                class="image-show">
              </iron-image>
```
```javascript
      properties: {       
        uploadState: {
          type: Array,
          value: function() {
            var arr = Array.apply(null, Array(5));
            var newArray = arr.map(()=> {
              return { 
                value: false,
                main: false,
                edited: false,
                loading: false
              };
            });
            return newArray;
          },
          notify: true
        },
```
##### outcome:
```
Request URL:http://70.1.42.2:3000/false
````
### Browsers Affected

- [ x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by bicknellr** [comment]
I'm not really convinced that this is an iron-image issue: it doesn't make sense that this only occurs when using the path syntax in a computed binding. Here's my repro attempt with iron-image's `preventLoad` property being set by a computed binding with a path syntax parameter: [demo](https://twisty-drill.glitch.me/twisty-drill/), [code](https://glitch.com/edit/#!/twisty-drill?path=src/index.html:1:0). Is that an accurate repro attempt? If so, maybe double check that you're using all the right [property modifying incantations](https://www.polymer-project.org/1.0/docs/devguide/model-data)? If not, could you provide a failing setup?

**Comment by dman777** [comment]
Thanks for taking the time to investigate this. I remixed the glitch so I could modify it. But when I run it, I just get a directory listing. 
 
It's not really an accurate run. For instance, upon the element becoming active the image(using iron pages) should not load be default as the data path will be `!false`. 

I also *suspect* a change in the data path in the `src="[[getImage(uploadState.*, index, 'value')]]"` causes iron image to load even when prevent load is true.

**Comment by bicknellr** [comment]
Hmm, looks like something that bower does now fails in glitch's setup - [here's the demo in jsbin instead](http://jsbin.com/qezihi/2/edit?html,output).

**Comment by dman777** [comment]
Thanks! I was able to reproduce the error here http://jsbin.com/jafecat/edit?html,output 

With `prevent-load="[[editState(uploadState.*, index, 'edited')]]"` and `edited: false` default, the image loads when it should not.

**Comment by dman777** [comment]
Thanks! Is there a way to get Polymer 1.7.1 in there? I tried ` <base href="//polygit2.appspot.com/webcomponentsjs+:v1/custom-elements+webcomponents+:master/shadydom+webcomponents+:master/shadycss+webcomponents+:master/polymer+:1.7.1/components/">` to no success

**Comment by bicknellr** [comment]
Yup, the hybrid elements should support [at least Polymer 1.9](https://github.com/PolymerElements/iron-image/blob/50cd4f97d43cf3d956b64b854b395e81414a1fc1/bower.json#L22); [here's a version of the jsbin that uses it](http://jsbin.com/rayibus/4/edit?html,output). However, while updating this, I noticed that there's a bug where if you set `preventLoad` to true and then change `src` multiple times but set it back to the original value last, then the image won't reload if you change `preventLoad` back to true. Maybe that's the problem you're running into?

**Comment by bicknellr** [comment]
(Opened #122.)

**Comment by bicknellr** [comment]
(#122 is closed as of v2.1.2.)

**Comment by dman777** [comment]
Thank you so much for the json bin.... I was able to reproduce the issue here:

http://jsbin.com/jafecat/edit?html,output

When you hit run, the image will load even though the `!false` is the value in `prevent-load="[[!editState(uploadState.*, index, 'edited')]]"`

**Comment by bicknellr** [comment]
Oh, it looks like the referenced `index` property doesn't exist. If you replace `index` with a literal or give it a default value in `properties` then it seems to work.

**Comment by dman777** [comment]
I think there is something wrong with JSBIN running  Polymer. I have:

http://jsbin.com/jafecat/edit?html,console,output

```
         editState: function(change, index, path) {
            console.log('nothing in here will show')
            return this.get(`uploadState.${index}.edited`);
          },
```

And I do not see the `console.log` statement at all. It looks as if the computed binding `editState` is not being called at all.

**Comment by bicknellr** [comment]
Try putting this inside `properties`:
```js
index: {
  type: Number,
  value: 2,
},
```

**Comment by dman777** [comment]
Closing...this was a timing issue in my code base. Thank you for investigating.
