### ISSUE TITLE
How to give the image style to fit the div ?

### ISSUE THREAD

**Issue by rajasimon** [PolymerElements/iron-image#13]
I want the iron-image to work exactly what img do...

    <img src="[[item.image.url]]" style='height: 100%; width: 100%; object-fit: contain'>

I tried with 

    <iron-image src="[[item.image.url]]" style='height: 470px; width: 836px;'  sizing="cover" preload fade></iron-image>

It's perfectly fine in desktop browser but in my mobile is matched .. see the sample image below 

![screenshot_2015-07-09-11-07-16](https://cloud.githubusercontent.com/assets/6974101/8588674/e4b3f9a4-262a-11e5-8e2a-ba30b81a236b.png)

So what to do with mobile ?

Github repo: http://github.com/rajasimon/techienews

**Comment by joshuajohnson814** [comment]
I'm having a similar issue. The problem with contain is that the parent is responsible for determining the size whereas I would like the img to drive the dimensions. If there was a way to pass in display and width CSS properties to be used on the actual img tag this could be resolved. Right now I'm doing something like this as a workaround...

````
iron-image, iron-image /deep/ img {
  display: block;
  width: 100%;
}
````

My parent div has a width of 50% and this is the only way I could make the image fill up the parent and remain responsive. Opening up CSS variables would be helpful so I don't have to apply styles through deep.

**Comment by bicknellr** [comment]
also, https://github.com/PolymerElements/paper-card/issues/27 depends on this.

**Comment by bicknellr** [comment]
Just landed a PR which adds a couple custom CSS properties: `--iron-image-width` and `--iron-image-height`. These allow you to set the width / height of the wrapped `<img>`.

**Comment by zerodevx** [comment]
Hi @bicknellr 

I was wondering how do I set `max-width` or `max-height`? It's a use case I'm facing right now... ended up creating a fork.

It might be a good idea to expose a CSS mixin like `@apply(--iron-image-mixin);` on [`#img`](https://github.com/PolymerElements/iron-image/blob/master/iron-image.html#L82-L86) instead - much like how `--iron-image-placeholder` is done. This allows users to succinctly control / pass in a basket of other properties; and also helps future-proof the implementation to a degree.

Thanks so much,
J

**Comment by bicknellr** [comment]
Hi, @zerodevx, [this thread](https://github.com/PolymerElements/iron-image/issues/8) might be useful. Also, [this demo](http://jsbin.com/gijavirexu/edit?html,output) shows how to apply `max-width` to an `iron-image`.

**Comment by zerodevx** [comment]
@bicknellr LIFESAVER!! Thanks so much for taking the time. MUCH appreciated!

**Comment by bicknellr** [comment]
@zerodevx np!

**Comment by Stanleynd** [comment]
I am also having this thesame problem for the past few days, i created a parent div element with an id="container" as the name with another div inside the container div  with the class="site-content" and it's content then i called a background-image through css for this and i want the image to be fitted to this element alone very visible. Thanks in advance.

**Comment by Stanleynd** [comment]
I am also having this thesame problem for the past few days, i created a parent div element with an id="container" as the name with another div inside the container div  with the class="site-content" and it's content then i called a background-image through css for this and i want the image to be fitted to this element alone very visible. Thanks in advance.

**Comment by Stanleynd** [comment]
I am also having this thesame problem for the past few days, i created a parent div element with an id="container" as the name with another div inside the container div  with the class="site-content" and it's content then i called a background-image through css for this and i want the image to be fitted to this element alone very visible. Thanks in advance.
