### ISSUE TITLE
Load event?

### ISSUE THREAD

**Issue by myfreeweb** [PolymerElements/iron-image#15]
There should be a `on-loaded` event, not just a property.

**Comment by davidrissato** [comment]
There is, just watch for changes to this property.

Just put a ```<iron-list ... on-loaded-change="_imageLoaded">```

And declare a handler in your polymer definition:
```
_imageLoaded: function(e) { 
   // e is an instance of CustomEvent. Do whatever you need
}
```

**Comment by Zecat** [comment]
you mean on-loaded-change**d**

**Comment by bicknellr** [comment]
more details: https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#change-notification-protocol

**Comment by JohnsonChung** [comment]
I face a problem that when you use iron-image inside iron-list.
This on-loaded-change event will be fired every time when iron-image leave virtual view and back, event <img> is actually loaded.

**Comment by bicknellr** [comment]
Hi @JohnsonChung, could you file a new issue? Also, take a look through [CONTRIBUTING.md](https://github.com/PolymerElements/iron-image/blob/master/CONTRIBUTING.md). Thanks!
