### ISSUE TITLE
Bad state possible when reusing the element with multiple images

### ISSUE THREAD

**Issue by sfeast** [PolymerElements/iron-image#16]
Seeing this with iron-list currently, but I believe this is a general issue when re-using the element with multiple images. Reproduction:

1. Set preload to true on an iron-image element.
2. Set the src property to an image that is not available.
3. The placeholder is correctly shown.
4. Now set the src property to an available image.

Result:
The placeholder still shows.
Expected:
The available image should show.

**Comment by davidrissato** [comment]
I have some changes that you might include in this fix. They are related to preLoad functions which is behaving erratically.

My changes fixes the following issues when iron-image is reused in an iron-list:

- Preload image being displayed over the last image loaded
- Preload image being hidden before the new image is fully loaded (when you change image src quickly)

What can I do to contribute with those changes?

**Comment by davidrissato** [comment]
By the way, here are my changes:

```diff
--- iron-image.html.old	2015-10-14 12:30:37.000000000 -0300
+++ iron-image.html	2015-10-14 12:39:32.000000000 -0300
@@ -236,8 +236,8 @@
 
     observers: [
       '_transformChanged(sizing, position)',
-      '_loadBehaviorChanged(canLoad, preload, loaded)',
-      '_loadStateChanged(src, preload, loaded)',
+      '_loadBehaviorChanged(canLoad, preload, loaded, src)',
+      '_loadStateChanged(src, preload, loaded)'
     ],
 
     ready: function() {
@@ -293,6 +293,9 @@
     _srcChanged: function(newSrc, oldSrc) {
       if (newSrc !== oldSrc) {
         this.loaded = false;
+        if (this.requiresPreload) {
+          this.style.backgroundImage = null;
+        }
       }
     },
 
@@ -317,22 +320,23 @@
     },
 
     _loadBehaviorChanged: function() {
-      var img;
-
       if (!this.canLoad) {
         return;
       }
 
       if (this.requiresPreload) {
-        img = new Image();
-        img.src = this.src;
-
+        if (!this._imgPreLoad) {
+          // We need just one reference while loading, and we will it discard it immediatelly after loading.
+          // But if src changes while the last image was still loading, we will reuse our image instance
+          this._imgPreLoad = new Image();
+          this._imgPreLoad.onload = function() {
+            this.loading = false;
+            this.loaded = true;
+            this._imgPreLoad = null;
+          }.bind(this);
+        }
+        this._imgPreLoad.src = this.src;
         this.loading = true;
-
-        img.onload = function() {
-          this.loading = false;
-          this.loaded = true;
-        }.bind(this);
       } else {
         this.loaded = true;
       }
```

**Comment by sfeast** [comment]
I still think this sounds like a different issue, I'd recommend filing a new issue, forking the repo, adding your fixes in your fork & then submit a new pull request to fix the new issue.

**Comment by davidrissato** [comment]
Ok, I'll do that

**Comment by bicknellr** [comment]
Closing because you created #23.

**Comment by sfeast** [comment]
@bicknellr I didn't create #23, I only asked @davidrissato to create a new issue to avoid causing confusion with this issue - which looks to have happened now anyways :(

This issue is pretty simple & so is the fix, if someone could spend a couple minutes reviewing I think it would be useful to the Polymer community.

**Comment by bicknellr** [comment]
Thanks for the correction, @sfeast! Could you add tests for this issue in #17?
