### ISSUE TITLE
Preload placeholder image not being properly displayed

### ISSUE THREAD

**Issue by davidrissato** [PolymerElements/iron-image#23]
There are two problems related to placeholder images:

1) Preload image is being displayed over the last image loaded when iron-image component is reused
2) Preload image sometimes is being hidden before image is fully loaded (when you change image src quickly)

I made a JSBin to reproduce the problem. You need to scroll down the list very fast in order to see both problems (this way it will load a lot of images). Notice how pre-load appears over the last image loaded. And sometimes preload image disappears before new image is loaded.

http://jsbin.com/raleni/19/edit?html,output

This is the problem I reported in issue #16. I'm filing it here as a new issue. I'll fork and submit my fix shortly afterwards.

**Comment by davidrissato** [comment]
@bicknellr I just tested your changes and it seems to be working fine. If you want to check by yourself, I changed my original JSBin to point to your last commit: http://jsbin.com/raleni/44/edit?html,output

**Comment by bicknellr** [comment]
Good to hear. I've actually been testing things out using a modified version of your JSBin and was hoping to include it in the demo page. For the sake of making sure we're being legit when it comes to licensing, could you put it in a PR? You just can stick it in a new file anywhere - don't worry about cleaning it up; as long as it's in a PR (and because you've already signed the CLA) we'll be able to take it and adapt it.

**Comment by davidrissato** [comment]
Ok, I'll do that. But it is important change my image source, because I'm pointing to someone's else website. Although those images are beautiful and publicly visible in their website, I never asked site's owner if I could point to them.
If you have a suggestion for a image source that I can point to, I'll be glad to change my sample before submitting my PR. Otherwise I'll point it to a dummy image source address.
Additionally, do I have to put any special header comments or will you do it over there?
Please, let me know how do you prefer my PR.

**Comment by bicknellr** [comment]
However you'd like to submit it is fine, I'll make sure the license notices (if any) / image usage are alright before it gets integrated.

**Comment by sweco-semhul** [comment]
What is the sate of this issue? Any plan to merge @davidrissato´s solution?

**Comment by bicknellr** [comment]
#44 is in release v1.1.0 and later.
