### ISSUE TITLE
this.style.backgroundImage needs quotes

### ISSUE THREAD

**Issue by rchrd2** [PolymerElements/iron-image#32]
I had an issue with a URL that did not load when using the sizing property. I changed the code and it works now.

Before:
```
        this.style.backgroundImage = this.src ? 'url(' + this.src + ')': '';
```
After:
```
        this.style.backgroundImage = this.src ? 'url("' + this.src + '")': '';
```

The example markup was:
```
<iron-image sizing="cover" style="width: 400px; height: 400px" preload src="uploads/screenshot-modesto craigslist org 2015-06-08 22-42-27.png"></iron-image>
```

I can submit a pull request for this if necessary.

**Comment by alefwmm** [comment]
+1. Same problem here.

**Comment by notwaldorf** [comment]
@rchrd2 A PR would be awesome! 🎉

**Comment by alefwmm** [comment]
I have forked the repository and did the changes by now. The changes are very small, so I do not think a PR is required. What do you think?

https://github.com/alefwmm/iron-image/commit/8fc2baa6e6e0391c78d0fbabb1de2735db81ef25

**Comment by bicknellr** [comment]
PolymerElements/iron-image#37

**Comment by bicknellr** [comment]
[This line](https://github.com/PolymerElements/iron-image/pull/44/files#diff-3005a2eaefe34d5d0afb8d08687f8aaeR301) and [this line](https://github.com/PolymerElements/iron-image/pull/44/files#diff-3005a2eaefe34d5d0afb8d08687f8aaeR380) should handle this, for the image itself (when sized) and the placeholder.
