### ISSUE TITLE
Handle src url errors

### ISSUE THREAD

**Issue by opus1269** [PolymerElements/iron-image#36]
The element doesn't let you know when a url is bad. It also does not handle re-setting the src after it was set to a bad url correctly. I have submitting a pull request to address this.

#35

**Comment by Negashev** [comment]
+1

**Comment by kevin-wise-infusionsoft** [comment]
Seems like this is a duplicate of #33

**Comment by opus1269** [comment]
Yes. I'm not concerned about the implementation details, as long as there is a property indicating the load failed and you can set the src after querying that.

**Comment by jonnenauha** [comment]
#33 was closed due to the fallback src. I kind of agree it gets a bit too complicated with it. This #35 looks simple and fixes real issues. The error bool will allow people to implement their own fallback mechanism (also, as setting src again is now supported without hacks ;)

**Comment by bicknellr** [comment]
Release 1.1.0 now includes `error` property support.
