### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by asmedrano** [PolymerElements/iron-image#42]
What events does this element broadcast? I noticed the tests included use of `loaded-changed`. Is there documentation for that somewhere?

**Comment by bicknellr** [comment]
Currently, `iron-image` doesn't fire any events itself.

The `-changed` prefixed events are fired whenever  a property with `notify: true` is changed. (See [here](https://www.polymer-project.org/1.0/docs/devguide/properties.html#notify) for more details.)
