### ISSUE TITLE
Disable background color placeholder once loaded

### ISSUE THREAD

**Issue by emanuelet** [PolymerElements/iron-image#49]
HI,
I will like to know if someone has an idea on how to achieve the following:
 - set the iron image to a background color to use as placeholder
 - letting the image to load
 - once the image is loaded, remove or disable the color background
I'm sure there is should be a way, but so far none of my attempts as been successful.

This is an example of one of them:
```html
<iron-image style="width:100%; height:360px; background-color: lightgray;" hidden$="[[!loadedImg]]" loaded="{{loadedImg}}" sizing="contain" preload fade src="http://lorempixel.com/800/360" ></iron-image>
```

Thanks in advance.

Cheers

**Comment by bicknellr** [comment]
I think [this JSBin](http://jsbin.com/keceja/edit?html,output) should point you in the right direction.

**Comment by emanuelet** [comment]
Thanks very much. With my implementation I had to register a style module, and it worked like a charm. 
Much appreciated.
