### ISSUE TITLE
Docs: computed props should be private or have doc strings.

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/iron-image#53]
https://github.com/PolymerElements/iron-image/blob/master/iron-image.html#L234-L239

`requiresPreload` and `canLoad` should have doc strings or be private (prefixed with "_") so they're not picked up in the docs:

https://elements.polymer-project.org/elements/iron-image#canLoad

**Comment by bicknellr** [comment]
#44 removes these properties.
