### ISSUE TITLE
How to set `border-radius`

### ISSUE THREAD

**Issue by BartKoppelmans** [PolymerElements/iron-image#65]
Hello,

At the moment I've got my code such that an image is shown, however since the sizing is set, the border radius does not apply to the image. Is there any solution to this?

**Comment by bicknellr** [comment]
border-radius + cover seems to be working: http://jsbin.com/zizafe/1/edit?html,output
Can you include code to repro? (I'll reopen then.) Also, make sure you haven't added `overflow: visible;` to the iron-image somewhere.

**Comment by BartKoppelmans** [comment]
I can't find a way to reproduce it. I could share a link to my site and show that, but that won't suffice. I guess I've got something wrong, but I can't find it. There is no `overflow: visible` to the iron-image and there is nothing else that could be the problem. The only thing I found to solve it, was to remove the sizing.

I guess I have to get back to the /deep/ and force the border-radius on the `sizedImgDiv`.

**Comment by bicknellr** [comment]
What browser are you seeing this in? @balloob is seeing the same thing (#65).

**Comment by BartKoppelmans** [comment]
I'm using Chrome version 50.0.2644.0 canary (64-bit)

**Comment by balloob** [comment]
I experienced the issue on Chrome 49.0.2623.39 beta (64-bit) using iron-image v1.2.2.

FWIW, I experienced the issue in [this webcomponent](https://github.com/balloob/home-assistant-polymer/blob/8ac32cd307470cb3f822452141d9cc59092ceebc/src/components/ha-label-badge.html#L69-L71) after upgrading my dependencies.

Applied CSS is `border-radius: 50%` and the `fit` class which translates to
```css
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
```

The [demo of Home Assistant](https://home-assistant.io/demo/) shows the older version of iron-image being used with the `border-radius` working (the badges on the top that contain images + the Chromecast entry)

**Comment by GrahenKraken** [comment]
I have the same issue inside of Cordova 6 + Crosswalk 16. Literally just did 'bower update' and the radius is broken.

**Comment by ozasadnyy** [comment]
Any updates here?

**Comment by bicknellr** [comment]
Hey, @bwh-rl, since you were able to repro and send a PR, do you have any extra info you could provide on your environment? I'm still having trouble with this. :/

**Comment by bwh-rl** [comment]
This is strange - I am not able to reproduce this myself. In our app the issue occurs. But in an test case i am not able to reproduce it. Going to do more tests.

What i know now is that it's somehow connected to the `position: absolute;` from the `#sizedImgDiv`.
And that these issue was not always present - Must have been either an browser or an polymer update.

Maybe some minor webkit bug that only occurs under special circumstances?

**Comment by bwh-rl** [comment]
Figured out that the issue occurs if an iron-list is present, it looks like the `transform` property triggers it - But only if it is in the paper-drawer-panel.
```
<paper-drawer-panel>
	<div drawer>
		<iron-image style="width:100px; height:100px; border-radius:50%;" sizing="cover" src="https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7Y1huOXVQdlFPMmM/materialdesign_introduction.png"></iron-image>
	</div>
	<div main>
		<div style="transform:translate3d(0px, 10px, 0px)">Transform element</div>
	</div>
</paper-drawer-panel>
```

**Comment by bicknellr** [comment]
@bwh-rl, thanks for whittling this down! [Your snippet repro's for me.](http://jsbin.com/vapafig/1/edit?html,output)

**Comment by bicknellr** [comment]
Weird, this definitely feels like a Blink bug: in that demo, if you move the transform property from inline to a rule, `overflow: hidden;` works as expected.

**Comment by NicolasRannou** [comment]
Any news on that?

**Comment by bicknellr** [comment]
Yeah, this is a Blink issue... [Here's a Polymer-less repro](http://jsbin.com/labipaqozo/1/edit?html,output) (visible in Chrome 49.0.2623.87 and 51.0.2682.0 canary). I'm going to try and reduce it more and then file a Blink bug.

**Comment by bicknellr** [comment]
Here we go:
```html
<html>
  <head>
    <style>
      .overflow-hidden {
        overflow: hidden;
        position: relative;
        width: 200px;
        height: 200px;
        border-radius: 50%;
      }

      .background-red {
        position: absolute;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        background: red;
      }
    </style>
  </head>
  <body>
    <div style="transform: translate3d(50px, 0px, 0px);">
      This text has a CSS transform in an inline style.
    </div>
    <div class="overflow-hidden">
      <div class="background-red"></div>
    </div>
  </body>
</html>
```
Toggle the inline transform in the inspector to see the bug.

**Comment by bicknellr** [comment]
Oh, this is a known bug: crbug.com/449107

**Comment by pimenteljchristopher** [comment]
any news to this issue? I'm struggling to modify id=sizedImgDiv

**Comment by pimenteljchristopher** [comment]
I found out the solution. 
  Add this to css div 
            transition: transform 350ms ease-in-out;
            will-change: transform;

**Comment by bicknellr** [comment]
@pimenteljchristopher and anyone else who comes here wondering about this, I can't see a consistent away to around this that isn't super hacky, so if this is a major problem for you please star the Chromium bug I've linked to. I think they use the star count as a rough metric for how many people are running into an issue in the wild.

**Comment by yairopro** [comment]
Untill the Chromium bug is solved, isn't there a way to workaround and force the `iron-image` to have `border-radius`?

After playing a little with the CSS properties on the `div#sizedImgDiv`, I saw it is possible to force the `border-radius` by disabling the `position : absolute`, and setting its dimensions to `height : 100%; width : 100%` instead.
