### ISSUE TITLE
Prevent load still loads the images if the src is set

### ISSUE THREAD

**Issue by tdctaz** [PolymerElements/iron-image#94]
### Description

The preventLoad does not work when the src has been set on `iron-image`
### Expected outcome

Expected that the image would not be loaded until `preventLoad` was set to false
### Actual outcome

Image was loaded
### Live Demo

```
  <iron-image src="http://publicdomainarchive.com/wp-content/uploads/2016/01/public-domain-images-free-stock-photos-001-1000x667.jpg" preventLoad>
  </iron-image>
```
### Browsers Affected

- [X] Chrome
- [?] Firefox
- [?] Safari 9
- [?] Safari 8
- [?] Safari 7
- [?] Edge
- [?] IE 11
- [?] IE 10

**Comment by bwh-rl** [comment]
preventLoad should be prevent-load as an attribute.
Though, it still does not work for me either.
```
<iron-image prevent-load src="[[somesourcepath]]"></iron-image>
```
gives me an undefined when i log this.preventLoad inside the _srcChanged.
Since boolean are true if the attribute is set and false if not, it should never be undefined?

https://jsbin.com/jubebabeme/edit?html,output

**Comment by stramel** [comment]
bump, any news on this? I am still seeing the issue.

**Comment by stramel** [comment]
I believe this has been addressed in the 2.0 release.

**Comment by bicknellr** [comment]
^ Yup, should be fixed.

**Comment by dman777** [comment]
[stackoverflow post](https://stackoverflow.com/questions/44600620/iron-image-prevent-load-not-working-off-of-data-path-binding)

This works for me with a normal boolean variable in the data binding, but not if a array data path value is used. Any ideas why?

**Comment by dman777** [comment]
@bicknellr This is still a issue. When using  data path for src and it detects a change, it will try to load the image even if `preventLoad` is true. Can you re-open, please? 

iron-image 2.1.1 / Polymer 1.*

```html
              <iron-image 
                hidden$="[[editState(uploadState.*, index, 'edited')]]"
                id="editIronImage"
                prevent-load="[[preventLoad]]"
                auto="false"
                src="[[HOST]][[IMAGES]][[getImage(uploadState.*, index, 'value')]]"
                sizing="cover"
                class="image-show">
              </iron-image>
```

```javascript
      rawRemoveImage: function(index, url) {
        var request =
          new Request(url, {
            credentials: 'include',
            mode: 'cors',
            method: 'DELETE'
          });

        fetch(request)
          .then(this.fetchError.bind(this))
          .then((response)=> {
            this.preventLoad = true;
            this.set(`uploadState.${index}.value`, false);
            this.set(`uploadState.${index}.edited`, true);
          })
          .catch((e) => {
            console.log(e);
          });
 ```

**Comment by bicknellr** [comment]
(closing again because you opened #119)
