### ISSUE TITLE
a href: add clickable link to iron-image

### ISSUE THREAD

**Issue by mbana** [PolymerElements/iron-image#97]
I see myself doing a lot. I wonder if other people are also doing it.
I am trying to avoid doing:

```javascript
      <a href$="[[clickUrl]]">
        <iron-image src="[[imgSrc]]"></iron-image>
      </a>
```

**Comment by davidrissato** [comment]
I see no reason to include this concern to iron-image, as long it is possible to achieve the same behavior using a tag clearly specialized to do what you want (in this case, the A tag).
If you included href in iron-image, you would also need to include target, alt and many other A tag attributes in iron-image, that would only unnecessarily bloat its namespace and its code.
